.TH armangrewal007 1 "September 2024" "version 0.1.3" "User Commands"
.SH NAME
armangrewal007 \- CLI to display Arman Singh Grewal's resume.
.SH SYNOPSIS
.B armangrewal007
[options]
.SH DESCRIPTION
This command-line tool displays the resume of Arman Singh Grewal.
.SH OPTIONS
.SH EXAMPLES
Run the command:
.B
armangrewal007

